# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zJejwKYAagWZXdbK1sYG6xk7hiw0SP4
"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='3'

import tensorflow as tf
from tensorflow import  keras
from PIL import Image
import numpy as np
import sys

jsonConfigPath=sys.argv[1]
weightsPath=sys.argv[2]
filePath=sys.argv[3]


with open(jsonConfigPath) as json_file:
  jsonConfig=json_file.read()
model= keras.models.model_from_json(jsonConfig)
model.load_weights(weightsPath)


image = tf.keras.preprocessing.image.load_img(filePath, target_size=(150,150,3))
inputArr= tf.keras.preprocessing.image.img_to_array(image)
inputArr= np.array([inputArr])

pred = tf.keras.activations.sigmoid(model.predict(inputArr))
if pred<0.5:
  label='cat'
  prob=1-pred
else:
  label='dog'
  prob=pred

print(f'The pet is a {label} with probability of {prob}')